#!/bin/bash

NAME="ipastorewebsite"                                  # Name of the application
DJANGODIR=/srv/sites/ipa-store/ipastorewebsite/                     # Django project directory
SOCKFILE=/srv/sites/ipa-store/ipastorewebsite/run/gunicorn.sock     # we will communicte using this unix socket
USER=deploy                                    # the user to run as
GROUP=deploy                                     # the group to run as
NUM_WORKERS=1                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=ipastorewebsite.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=ipastorewebsite.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /usr/local/virtualenvs/ipastorewebsite/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /usr/local/virtualenvs/ipastorewebsite/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  #--bind=unix:$SOCKFILE \
  --bind=127.0.0.1:8000 \
  --log-level=debug \
  --log-file=/home/ubuntu/logs/ipastorewebsite.log

